print("Programmu izstrtādāja: Evelīna Elza Cillinberga.")
print()
print("Laukuma aprēķins ģeometriskajām figūrām")
print("     ****")
print("Ievadiet malas A garumu:")
mala_a = float(input())
print("Malas A garums: ", mala_a)
print("     ****")
print("Ievadiet malas B garumu:")
mala_b = float(input())
print("Malas B garums: ", mala_b)
print("     ****")
print("Ievadiet augstumu:")
augstums = float(input())
print("Augstums: ", float(augstums))
print("Laukums trijstūrim: ", (mala_a*augstums)/2)
print("Laukums trapecei: ", ((mala_a+mala_b)/2)*augstums)
print("Laukums paralelogramam: ", mala_a*augstums)
print("     ****")
print("Paldies!")